-- ════════════════════════════════════════════════════════════════════════════
-- Seeds SXT's real timber seasoning price list (plank per sqft, beam per LFT).
-- Source: printed "Price List For Timber Seasoning" + plank rate sheet.
-- Safe to re-run — upserts on (entity_id, service, thickness) / (..., height, width).
-- ════════════════════════════════════════════════════════════════════════════

-- ── Plank rates (per sqft) ────────────────────────────────────────────────────
-- thickness -> (impregnation rate, kiln_drying rate)
insert into plank_treatment_rates (entity_id, service, thickness, rate_per_sqft) values
  ('SXT', 'impregnation', '5/8"',   43),
  ('SXT', 'kiln_drying',  '5/8"',   23),
  ('SXT', 'impregnation', '3/4"',   50),
  ('SXT', 'kiln_drying',  '3/4"',   28),
  ('SXT', 'impregnation', '7/8"',   58),
  ('SXT', 'kiln_drying',  '7/8"',   32),
  ('SXT', 'impregnation', '1/2"',   35),
  ('SXT', 'kiln_drying',  '1/2"',   18),
  ('SXT', 'impregnation', '1"',     65),
  ('SXT', 'kiln_drying',  '1"',     36),
  ('SXT', 'impregnation', '1-1/8"', 73),
  ('SXT', 'kiln_drying',  '1-1/8"', 39),
  ('SXT', 'impregnation', '1-3/8"', 80),
  ('SXT', 'kiln_drying',  '1-3/8"', 43),
  ('SXT', 'impregnation', '1-1/2"', 88),
  ('SXT', 'kiln_drying',  '1-1/2"', 50),
  ('SXT', 'impregnation', '1-5/8"', 95),
  ('SXT', 'kiln_drying',  '1-5/8"', 51),
  ('SXT', 'impregnation', '1-3/4"', 103),
  ('SXT', 'kiln_drying',  '1-3/4"', 55),
  ('SXT', 'impregnation', '1-7/8"', 110),
  ('SXT', 'kiln_drying',  '1-7/8"', 58),
  ('SXT', 'impregnation', '2"',     118),
  ('SXT', 'kiln_drying',  '2"',     64),
  ('SXT', 'impregnation', '2-1/4"', 125),
  ('SXT', 'kiln_drying',  '2-1/4"', 69),
  ('SXT', 'impregnation', '2-1/2"', 140),
  ('SXT', 'kiln_drying',  '2-1/2"', 75),
  ('SXT', 'impregnation', '3"',     155),
  ('SXT', 'kiln_drying',  '3"',     83),
  ('SXT', 'impregnation', '3-1/4"', 185),
  ('SXT', 'kiln_drying',  '3-1/4"', 96),
  ('SXT', 'impregnation', '3-1/2"', 215),
  ('SXT', 'kiln_drying',  '3-1/2"', 112)
on conflict (entity_id, service, thickness) do nothing;

-- ── Beam rates (per LFT) ──────────────────────────────────────────────────────
-- height x width -> (impregnation rate, kiln_drying rate)
insert into beam_treatment_rates (entity_id, service, height, width, rate_per_lft) values
  ('SXT', 'impregnation', '1"',     '2"',     15),
  ('SXT', 'kiln_drying',  '1"',     '2"',     12),
  ('SXT', 'impregnation', '1-1/2"', '1-1/2"', 17),
  ('SXT', 'kiln_drying',  '1-1/2"', '1-1/2"', 13),
  ('SXT', 'impregnation', '2"',     '2"',     25),
  ('SXT', 'kiln_drying',  '2"',     '2"',     16),
  ('SXT', 'impregnation', '2-1/2"', '1-3/4"', 25),
  ('SXT', 'kiln_drying',  '2-1/2"', '1-3/4"', 16),
  ('SXT', 'impregnation', '1-1/4"', '4"',     30),
  ('SXT', 'kiln_drying',  '1-1/4"', '4"',     18),
  ('SXT', 'impregnation', '2"',     '3"',     35),
  ('SXT', 'kiln_drying',  '2"',     '3"',     19),
  ('SXT', 'impregnation', '2-1/4"', '3-1/4"', 42),
  ('SXT', 'kiln_drying',  '2-1/4"', '3-1/4"', 22),
  ('SXT', 'impregnation', '2"',     '4"',     45),
  ('SXT', 'kiln_drying',  '2"',     '4"',     26),
  ('SXT', 'impregnation', '2-1/2"', '3-1/2"', 49),
  ('SXT', 'kiln_drying',  '2-1/2"', '3-1/2"', 27),
  ('SXT', 'impregnation', '3"',     '3"',     50),
  ('SXT', 'kiln_drying',  '3"',     '3"',     27),
  ('SXT', 'impregnation', '2-1/4"', '4-1/4"', 53),
  ('SXT', 'kiln_drying',  '2-1/4"', '4-1/4"', 29),
  ('SXT', 'impregnation', '2-1/2"', '4"',     55),
  ('SXT', 'kiln_drying',  '2-1/2"', '4"',     31),
  ('SXT', 'impregnation', '2"',     '5"',     55),
  ('SXT', 'kiln_drying',  '2"',     '5"',     31),
  ('SXT', 'impregnation', '2"',     '6"',     65),
  ('SXT', 'kiln_drying',  '2"',     '6"',     36),
  ('SXT', 'impregnation', '3"',     '4"',     65),
  ('SXT', 'kiln_drying',  '3"',     '4"',     36),
  ('SXT', 'impregnation', '3-1/2"', '3-1/2"', 67),
  ('SXT', 'kiln_drying',  '3-1/2"', '3-1/2"', 36),
  ('SXT', 'impregnation', '3"',     '4-1/2"', 73),
  ('SXT', 'kiln_drying',  '3"',     '4-1/2"', 40),
  ('SXT', 'impregnation', '2"',     '7"',     75),
  ('SXT', 'kiln_drying',  '2"',     '7"',     41),
  ('SXT', 'impregnation', '3"',     '5"',     80),
  ('SXT', 'kiln_drying',  '3"',     '5"',     44),
  ('SXT', 'impregnation', '2-1/2"', '6"',     80),
  ('SXT', 'kiln_drying',  '2-1/2"', '6"',     44),
  ('SXT', 'impregnation', '4"',     '4"',     85),
  ('SXT', 'kiln_drying',  '4"',     '4"',     47),
  ('SXT', 'impregnation', '2-1/2"', '6-1/2"', 87),
  ('SXT', 'kiln_drying',  '2-1/2"', '6-1/2"', 48),
  ('SXT', 'impregnation', '3-1/2"', '5"',     92.5),
  ('SXT', 'kiln_drying',  '3-1/2"', '5"',     49),
  ('SXT', 'impregnation', '3"',     '6"',     95),
  ('SXT', 'kiln_drying',  '3"',     '6"',     51),
  ('SXT', 'impregnation', '4"',     '5"',     105),
  ('SXT', 'kiln_drying',  '4"',     '5"',     56),
  ('SXT', 'impregnation', '2-1/2"', '8-1/2"', 112),
  ('SXT', 'kiln_drying',  '2-1/2"', '8-1/2"', 63),
  ('SXT', 'impregnation', '4"',     '6"',     125),
  ('SXT', 'kiln_drying',  '4"',     '6"',     66),
  ('SXT', 'impregnation', '4"',     '6-1/2"', 135),
  ('SXT', 'kiln_drying',  '4"',     '6-1/2"', 71),
  ('SXT', 'impregnation', '4"',     '7"',     145),
  ('SXT', 'kiln_drying',  '4"',     '7"',     78),
  ('SXT', 'impregnation', '5"',     '6"',     155),
  ('SXT', 'kiln_drying',  '5"',     '6"',     81),
  ('SXT', 'impregnation', '4"',     '8"',     165),
  ('SXT', 'kiln_drying',  '4"',     '8"',     86),
  ('SXT', 'impregnation', '7"',     '10"',    355),
  ('SXT', 'kiln_drying',  '7"',     '10"',    208),
  ('SXT', 'impregnation', '6"',     '12"',    365),
  ('SXT', 'kiln_drying',  '6"',     '12"',    212)
on conflict (entity_id, service, height, width) do nothing;
